### ISSUE TITLE
Can't kill Safari

### ISSUE THREAD

**Issue by robdodson** [GoogleChromeLabs/selenium-assistant#104]
Not sure if this is related to #45 but I noticed `return seleniumAssistant.killWebDriver(driver);` doesn't kill Safari. Works on Chrome and Firefox though :)

**Comment by gauntface** [comment]
I know I'm a little late to this. I'm hooking adding technology preview support for safari and it looks like I can set everything is closing as I'd expect *apart from* the safari app stays  open in the dock - but the window actually closes.

Is that what you were experiencing?

**Comment by robdodson** [comment]
Can't recall now :P

Just tried with the latest and i'm seeing the same behavior you describe. Safari window closes, but the dock icon is still present. Not a huge deal IMO

**Comment by robdodson** [comment]
Sorry, didn't mean to close. I'll leave it up to you if you want this to remain open as a reminder or anything. Otherwise I'm cool if you close it.

**Comment by gauntface** [comment]
Ill close for now - but will likely dig into it more.
