### ISSUE TITLE
Support for simultaneous browser downloads

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChromeLabs/selenium-assistant#110]
See https://github.com/GoogleChrome/workbox/pull/1284#discussion_r167052632 for context.

Sequential downloads via a series of `await seleniumAssistant.downloadLocalBrowser()` worked fine in the Travis CI environment, but making the downloads simultaneous via

```javascript
const downloadPromises = [
  seleniumAssistant.downloadLocalBrowser('chrome', 'stable', expiration),
  seleniumAssistant.downloadLocalBrowser('chrome', 'beta', expiration),
  // ...
];
await Promise.all(downloadPromises);
```

led to what appears to be a failure getting Firefox properly unpackaged.

**Comment by gauntface** [comment]
This isn't actionable given no error was thrown and the API provided by selenium is the same. I've not seen this in any of the other numerous projects doing this.
