### ISSUE TITLE
Remove code for download Opera on Linux

### ISSUE THREAD

**Issue by gauntface** [GoogleChromeLabs/selenium-assistant#33]
Opera doesn't have a sane way to grab latest version of stable, beta and developer versions on linux (They do on OS X).

I've reached out to Opera to try and find a solution.

**Comment by gauntface** [comment]
@andreasbovens any ideas how I can download the latest stable, beta and unstable for linux?

**Comment by gauntface** [comment]
Going to leave this issue open for tracking deletion of current Opera code.

**Comment by gauntface** [comment]
https://deb.opera.com/manual.html

**Comment by jeffposnick** [comment]
Opera supported has been removed (see #120).
